# DS 2.1 notes

In [69]:
import pandas as pd 
import numpy as np
  
# initialize list of lists 
data = [[1000, 2], [1500, 3]]
  
# Create the pandas DataFrame 
df = pd.DataFrame(data, columns = ['x', 'y']) 
  
# print dataframe. 
df

x  y
0  1000  2
1  1500  3

# Min Max Scaler
---

In [74]:
def max_min_scaler(matrix):
    return pd.DataFrame(zip(*[(np.array(matrix[column]) - min(matrix[column])) / (max(matrix[column]) - (min(matrix[column]))) for column in matrix]), columns = matrix.columns)
max_min_scaler(df)

x    y
0  0.0  0.0
1  1.0  1.0

In [75]:
new_df = df.copy()
for column in df:
    col_range = max(df[column]) - min(df[column])
    col_arr = np.array(df[column])
    col_arr -= min(col_arr)
    col_arr = col_arr / col_range
    new_df[column] = col_arr
new_df

x    y
0  0.0  0.0
1  1.0  1.0

## Use sklearn to do it for us

In [81]:
import sklearn
sklearn.__version__

'0.21.2'

In [79]:
from sklearn import preprocessing


X_train = np.array([[1000, 2], [1500, 3]])

min_max_scaler = preprocessing.MinMaxScaler()
X_minmax = min_max_scaler.fit_transform(X_train)
print(X_minmax)

[[0. 0.]
 [1. 1.]]


## Standard Scaling

### Do it yourself:

In [109]:
def standard_scaler(np_matrix):
    return (np_matrix - np_matrix.mean(axis=0)) / np_matrix.std(axis=0)
standard_scaler(X_train)

array([[-1., -1.],
       [ 1.,  1.]])

### Let sklearn do it

In [108]:
from sklearn import preprocessing

standard_scaler = preprocessing.StandardScaler()
standard_scaler.fit_transform(X_train)

array([[-1., -1.],
       [ 1.,  1.]])